namespace CslaGeneratorSerialization.Models;

internal sealed record SerializationItemModel(string PropertyInfoFieldName, TypeReferenceModel PropertyInfoContainingType, TypeReferenceModel PropertyInfoDataType);