using NUnit.Framework;

namespace CslaGeneratorSerialization.Tests.Generators.Graphs;

public static class CommandBaseTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			namespace Domains;

			[GeneratorSerializable]
			public sealed partial class Operation
				: CommandBase<Operation>
			{
				public static readonly PropertyInfo<string> StringContentsProperty =
					RegisterProperty<string>(_ => _.StringContents);
				public string StringContents
				{
					get => this.ReadProperty(Operation.StringContentsProperty);
					set => this.LoadProperty(Operation.StringContentsProperty, value);
				}
						
				public static readonly PropertyInfo<int> Int32ContentsProperty =
					RegisterProperty<int>(_ => _.Int32Contents);
				public int Int32Contents
				{
					get => this.ReadProperty(Operation.Int32ContentsProperty);
					set => this.LoadProperty(Operation.Int32ContentsProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class Operation
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Operation.Int32ContentsProperty
					context.Writer.Write(this.ReadProperty<int>(global::Domains.Operation.Int32ContentsProperty));
					
					// global::Domains.Operation.StringContentsProperty
					context.Writer.Write(this.ReadProperty<string>(global::Domains.Operation.StringContentsProperty));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Operation.Int32ContentsProperty
					this.LoadProperty(global::Domains.Operation.Int32ContentsProperty, context.Reader.ReadInt32());
					
					// global::Domains.Operation.StringContentsProperty
					this.LoadProperty(global::Domains.Operation.StringContentsProperty, context.Reader.ReadString());
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[
				(typeof(GeneratorSerializationGenerator), "Domains.Operation_GeneratorSerialization.g.cs", generatedCode),
			],
			[]);
	}
}