using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.ValueTypes;

internal static class ClaimsPrincipalGeneratorTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;
			using System.Security.Claims;

			#nullable enable

			namespace Domains;

			[GeneratorSerializable]
			public sealed partial class Data
				: BusinessBase<Data>
			{
				public static readonly PropertyInfo<ClaimsPrincipal> ContentsProperty =
					RegisterProperty<ClaimsPrincipal>(_ => _.Contents);
				public ClaimsPrincipal Contents
				{
					get => this.GetProperty(Data.ContentsProperty)!;
					set => this.SetProperty(Data.ContentsProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class Data
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Data.ContentsProperty
					var value0 = this.ReadProperty<global::System.Security.Claims.ClaimsPrincipal>(global::Domains.Data.ContentsProperty);
						
					if (value0 is not null)
					{
						(var isReferenceDuplicate, var referenceId) = context.GetReference(value0);
						
						if (isReferenceDuplicate)
						{
							context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Duplicate);
							context.Writer.Write(referenceId);
						}
						else
						{
							context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
					
							using (var value0stream = new global::System.IO.MemoryStream())
							{
								using (var value0writer = new global::System.IO.BinaryWriter(value0stream))
								{
									value0.WriteTo(value0writer);
									var value0buffer = value0stream.ToArray();
									context.Writer.Write((value0buffer.Length, value0buffer));
								}
							}
						}
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Data.ContentsProperty
					switch (context.Reader.ReadStateValue())
					{
						case global::CslaGeneratorSerialization.SerializationState.Duplicate:
							this.LoadProperty(global::Domains.Data.ContentsProperty, context.GetReference(context.Reader.ReadInt32()));
							break;
						case global::CslaGeneratorSerialization.SerializationState.Value:
							var buffer = context.Reader.ReadByteArray();
						
							using (var stream = new global::System.IO.MemoryStream(buffer))
							{
								using (var reader = new global::System.IO.BinaryReader(stream))
								{
									var principal = new global::System.Security.Claims.ClaimsPrincipal(reader);
									this.LoadProperty(global::Domains.Data.ContentsProperty, principal);
									context.AddReference(principal);
								}
							}
							break;
						case global::CslaGeneratorSerialization.SerializationState.Null:
							break;
					}
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[("Domains.Data_GeneratorSerialization.g.cs", generatedCode)],
			[]);
	}
}