using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs.Unions;

internal static class UnionWithMultipleCasesTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable
			
			namespace Domains;

			public union Identifier(string, int, Guid);

			[GeneratorSerializable]
			public partial class Customer
				: BusinessBase<Customer>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<Identifier> IdentifierProperty =
					Customer.RegisterProperty<Identifier>(_ => _.Identifier);
				public Identifier Identifier
				{
					get => this.GetProperty(Customer.IdentifierProperty);
					set => this.SetProperty(Customer.IdentifierProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			using CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public partial class Customer
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Customer.IdentifierProperty
					var value0 = this.ReadProperty<global::Domains.Identifier>(global::Domains.Customer.IdentifierProperty)!;
					context.WriteUnion(value0, new global::System.Collections.Generic.List<uint>());
					
					// General Serialization
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Customer.IdentifierProperty
					{
						var typeIdentifiers = context.Reader.ReadUInt32Array();
						var typeIdentifiersIndex = -1;
						this.LoadProperty(global::Domains.Customer.IdentifierProperty, (global::Domains.Identifier)context.ReadUnion<global::Domains.Identifier>(typeIdentifiers, ++typeIdentifiersIndex));
					}
					
					// General Deserialization
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
					((global::Csla.Serialization.Mobile.ISerializationNotification)this).Deserialized();
				}
			}
			
			""";

		var readerExtensionsCode =
			"""
			// <auto-generated/>
			using CslaGeneratorSerialization.Extensions;
			
			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			internal static class GeneratorFormatterReaderContextExtensions
			{
				extension(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					public object ReadUnion<T>(uint[] typeIdentifiers, int typeIdentifiersIndex)
					{
						if (typeof(T) == typeof(global::Domains.Identifier))
						{
							switch(typeIdentifiers[typeIdentifiersIndex])
							{
								case 3:
									return (global::Domains.Identifier)null!;
								case 0:
									// string
									return (global::Domains.Identifier)context.Reader.ReadString();
								case 1:
									// int
									return (global::Domains.Identifier)context.Reader.ReadInt32();
								case 2:
									// global::System.Guid
									return (global::Domains.Identifier)new global::System.Guid(context.Reader.ReadBytes(16));
								default:
									throw new global::System.NotSupportedException($"Unexpected case identifier for type global::Domains.Identifier at index {typeIdentifiersIndex}: {typeIdentifiers[typeIdentifiersIndex]}");
							}
						}
						
						throw new global::System.NotSupportedException($"Unexpected union type: {typeof(T).FullName}");
					}
				}
			}
			
			""";

		var writerExtensionsCode =
			"""
			// <auto-generated/>
			using CslaGeneratorSerialization.Extensions;
			
			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			internal static class GeneratorFormatterWriterContextExtensions
			{
				extension(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					public void WriteUnion(global::Domains.Identifier value, global::System.Collections.Generic.List<uint> typeIdentifiers)
					{
						switch(value)
						{
							case null:
								typeIdentifiers.Add(3);
								context.Writer.Write((typeIdentifiers.Count, typeIdentifiers.ToArray()));
								break;
							case string u0:
								typeIdentifiers.Add(0);
								context.Writer.Write((typeIdentifiers.Count, typeIdentifiers.ToArray()));
								context.Writer.Write(u0);
								break;
							case int u1:
								typeIdentifiers.Add(1);
								context.Writer.Write((typeIdentifiers.Count, typeIdentifiers.ToArray()));
								context.Writer.Write(u1);
								break;
							case global::System.Guid u2:
								typeIdentifiers.Add(2);
								context.Writer.Write((typeIdentifiers.Count, typeIdentifiers.ToArray()));
								context.Writer.Write(u2);
								break;
						}
					}
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[
				("Domains.Customer_GeneratorSerialization.g.cs", generatedCode),
				("GeneratorFormatterReaderContextExtensions.g.cs", readerExtensionsCode),
				("GeneratorFormatterWriterContextExtensions.g.cs", writerExtensionsCode)
			],
			[]);
	}
}