using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs.Unions;

internal static class UnionOfClaimsPrincipalTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;
			using System.Security.Claims;
			
			#nullable enable
			
			namespace Domains;

			public union Identifier(ClaimsPrincipal);

			[GeneratorSerializable]
			public partial class Customer
				: BusinessBase<Customer>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<Identifier> IdentifierProperty =
					Customer.RegisterProperty<Identifier>(_ => _.Identifier);
				public Identifier Identifier
				{
					get => this.GetProperty(Customer.IdentifierProperty);
					set => this.SetProperty(Customer.IdentifierProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			using CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public partial class Customer
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Customer.IdentifierProperty
					var value0 = this.ReadProperty<global::Domains.Identifier>(global::Domains.Customer.IdentifierProperty)!;
					context.WriteUnion(value0, new global::System.Collections.Generic.List<byte>());
					
					// General Serialization
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Customer.IdentifierProperty
					{
						var typeIdentifiers = context.Reader.ReadByteArray();
						var typeIdentifiersIndex = -1;
						this.LoadProperty(global::Domains.Customer.IdentifierProperty, (global::Domains.Identifier)context.ReadUnion<global::Domains.Identifier>(typeIdentifiers, ++typeIdentifiersIndex));
					}
					
					// General Deserialization
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
					((global::Csla.Serialization.Mobile.ISerializationNotification)this).Deserialized();
				}
			}
			
			""";

		var readerExtensionsCode =
			"""
			// <auto-generated/>
			using CslaGeneratorSerialization.Extensions;
			
			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			internal static class GeneratorFormatterReaderContextExtensions
			{
				extension(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					public object ReadUnion<T>(byte[] typeIdentifiers, int typeIdentifiersIndex)
					{
						if (typeof(T) == typeof(global::Domains.Identifier))
						{
							switch(typeIdentifiers[typeIdentifiersIndex])
							{
								case 0:
									// global::System.Security.Claims.ClaimsPrincipal
									switch (context.Reader.ReadStateValue())
									{
										case global::CslaGeneratorSerialization.SerializationState.Duplicate:
											return (global::Domains.Identifier)(global::System.Security.Claims.ClaimsPrincipal)context.GetReference(context.Reader.ReadInt32())!;
										case global::CslaGeneratorSerialization.SerializationState.Value:
											var buffer = context.Reader.ReadByteArray();
										
											using (var stream = new global::System.IO.MemoryStream(buffer))
											{
												using (var reader = new global::System.IO.BinaryReader(stream))
												{
													var principal = new global::System.Security.Claims.ClaimsPrincipal(reader);
													context.AddReference(principal);
													return (global::Domains.Identifier)principal;
												}
											}
										case global::CslaGeneratorSerialization.SerializationState.Null:
											return (global::Domains.Identifier)(null as global::System.Security.Claims.ClaimsPrincipal)!;
									}
									break;
								default:
									throw new global::System.NotSupportedException($"Unexpected case identifier for type global::Domains.Identifier at index {typeIdentifiersIndex}: {typeIdentifiers[typeIdentifiersIndex]}");
							}
						}
						
						throw new global::System.NotSupportedException($"Unexpected union type: {typeof(T).FullName}");
					}
				}
			}
			
			""";

		var writerExtensionsCode =
			"""
			// <auto-generated/>
			using CslaGeneratorSerialization.Extensions;
			
			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			internal static class GeneratorFormatterWriterContextExtensions
			{
				extension(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					public void WriteUnion(global::Domains.Identifier value, global::System.Collections.Generic.List<byte> typeIdentifiers)
					{
						switch(value)
						{
							case global::System.Security.Claims.ClaimsPrincipal u0:
								typeIdentifiers.Add(0);
								context.Writer.Write((typeIdentifiers.Count, typeIdentifiers.ToArray()));
								if (u0 is not null)
								{
									(var isReferenceDuplicate, var referenceId) = context.GetReference(u0);
									
									if (isReferenceDuplicate)
									{
										context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Duplicate);
										context.Writer.Write(referenceId);
									}
									else
									{
										context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
								
										using (var u0stream = new global::System.IO.MemoryStream())
										{
											using (var u0writer = new global::System.IO.BinaryWriter(u0stream))
											{
												u0.WriteTo(u0writer);
												var u0buffer = u0stream.ToArray();
												context.Writer.Write((u0buffer.Length, u0buffer));
											}
										}
									}
								}
								else
								{
									context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
								}
								break;
						}
					}
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[
				("Domains.Customer_GeneratorSerialization.g.cs", generatedCode),
				("GeneratorFormatterReaderContextExtensions.g.cs", readerExtensionsCode),
				("GeneratorFormatterWriterContextExtensions.g.cs", writerExtensionsCode)
			],
			[]);
	}
}