namespace CslaGeneratorSerialization.Analysis.Tests.Generators;

public sealed class NamespaceTests
{
	[Test]
	public async Task CreateWhenBusinessObjectHasNoNamespaceAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable
			
			[GeneratorSerializable]
			public partial class Customer
				: BusinessBase<Customer>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<uint> AgeProperty =
					Customer.RegisterProperty<uint>(_ => _.Age);
				public uint Age
				{
					get => this.GetProperty(Customer.AgeProperty);
					set => this.SetProperty(Customer.AgeProperty, value);
				}

				public static readonly PropertyInfo<string> NameProperty =
					Customer.RegisterProperty<string>(_ => _.Name);
				public string Name
				{
					get => this.GetProperty(Customer.NameProperty)!;
					set => this.SetProperty(Customer.NameProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			public partial class Customer
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Customer.AgeProperty
					context.Writer.Write(this.ReadProperty<uint>(global::Customer.AgeProperty));
					
					// global::Customer.NameProperty
					var value1 = this.ReadProperty<string>(global::Customer.NameProperty)!;
					
					if (value1 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value1);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Customer.AgeProperty
					this.LoadProperty(global::Customer.AgeProperty, context.Reader.ReadUInt32());
					
					// global::Customer.NameProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Customer.NameProperty, context.Reader.ReadString());
					}
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[("Customer_GeneratorSerialization.g.cs", generatedCode)],
			[]);
	}
}