namespace CslaGeneratorSerialization.Analysis.Models;

internal sealed record SerializationItemModel(string PropertyInfoFieldName, ITypeReferenceModel PropertyInfoContainingType, ITypeReferenceModel PropertyInfoDataType);