using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs;

internal static class BusinessDocumentBaseTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable
			
			namespace Domains;

			[GeneratorSerializable]
			public partial class Customer
				: BusinessDocumentBase<Customer, Address>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<uint> AgeProperty =
					Customer.RegisterProperty<uint>(nameof(Customer.Age));
				public uint Age
				{
					get => this.GetProperty(Customer.AgeProperty);
					set => this.SetProperty(Customer.AgeProperty, value);
				}

				public static readonly PropertyInfo<string> NameProperty =
					Customer.RegisterProperty<string>(nameof(Customer.Name));
				public string Name
				{
					get => this.GetProperty(Customer.NameProperty)!;
					set => this.SetProperty(Customer.NameProperty, value);
				}
			}

			[GeneratorSerializable]
			public partial class Address
				: BusinessBase<Address>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<string> CityProperty =
					Address.RegisterProperty<string>(nameof(Address.City));
				public string City
				{
					get => this.GetProperty(Address.CityProperty)!;
					set => this.SetProperty(Address.CityProperty, value);
				}
			}
			""";

		var customerGeneratedCode =
			""""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public partial class Customer
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Customer.AgeProperty
					context.Writer.Write(this.ReadProperty<uint>(global::Domains.Customer.AgeProperty));
					
					// global::Domains.Customer.NameProperty
					var value1 = this.ReadProperty<string>(global::Domains.Customer.NameProperty)!;
					
					if (value1 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value1);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					context.Writer.Write(this.Count);
					
					foreach (var item in this)
					{
						context.Write(item, false);
					}
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Customer.AgeProperty
					this.LoadProperty(global::Domains.Customer.AgeProperty, context.Reader.ReadUInt32());
					
					// global::Domains.Customer.NameProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.Customer.NameProperty, context.Reader.ReadString());
					}
					
					var count = context.Reader.ReadInt32();
					
					for (var i = 0; i < count; i++)
					{
						this.Add(context.Read<global::Domains.Address>(false)!);
					}
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
					((global::Csla.Serialization.Mobile.ISerializationNotification)this).Deserialized();
				}
			}
			
			"""";

		var addressGeneratedCode =
			""""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public partial class Address
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Address.CityProperty
					var value0 = this.ReadProperty<string>(global::Domains.Address.CityProperty)!;
					
					if (value0 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value0);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Address.CityProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.Address.CityProperty, context.Reader.ReadString());
					}
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
					((global::Csla.Serialization.Mobile.ISerializationNotification)this).Deserialized();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[
				("Domains.Customer_GeneratorSerialization.g.cs", customerGeneratedCode),
				("Domains.Address_GeneratorSerialization.g.cs", addressGeneratedCode)
			],
			[]);
	}
}