using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs;

internal static class ChildBusinessObjectGeneratorTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable

			namespace Domains;

			[GeneratorSerializable]
			public sealed partial class Data
				: BusinessBase<Data>
			{
				public static readonly PropertyInfo<ChildData> ContentsProperty =
					RegisterProperty<ChildData>(_ => _.Contents);
				public ChildData Contents
				{
					get => this.GetProperty(Data.ContentsProperty)!;
					set => this.SetProperty(Data.ContentsProperty, value);
				}
			}

			[GeneratorSerializable]
			public sealed partial class ChildData
				: BusinessBase<ChildData>
			{
				public static readonly PropertyInfo<string> ChildContentsProperty =
					RegisterProperty<string>(_ => _.ChildContents);
				public string ChildContents
				{
					get => this.GetProperty(ChildData.ChildContentsProperty)!;
					set => this.SetProperty(ChildData.ChildContentsProperty, value);
				}
			}			
			""";

		var dataGeneratedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class Data
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Data.ContentsProperty
					context.Write(this.ReadProperty<global::Domains.ChildData>(global::Domains.Data.ContentsProperty), true);
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Data.ContentsProperty
					this.LoadProperty(global::Domains.Data.ContentsProperty, context.Read<global::Domains.ChildData>(true)!);
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		var childGeneratedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class ChildData
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.ChildData.ChildContentsProperty
					var value0 = this.ReadProperty<string>(global::Domains.ChildData.ChildContentsProperty)!;
					
					if (value0 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value0);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.ChildData.ChildContentsProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.ChildData.ChildContentsProperty, context.Reader.ReadString());
					}
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[
				("Domains.Data_GeneratorSerialization.g.cs", dataGeneratedCode),
				("Domains.ChildData_GeneratorSerialization.g.cs", childGeneratedCode)
			],
			[]);
	}

	[Test]
	public static async Task GenerateWhenChildObjectDoesNotParticipateInGeneratorSerializationAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable

			namespace Domains;

			[GeneratorSerializable]
			public sealed partial class Data
				: BusinessBase<Data>
			{
				public static readonly PropertyInfo<ChildData> ContentsProperty =
					RegisterProperty<ChildData>(_ => _.Contents);
				public ChildData Contents
				{
					get => this.GetProperty(Data.ContentsProperty)!;
					set => this.SetProperty(Data.ContentsProperty, value);
				}
			}

			public sealed class ChildData
				: BusinessBase<ChildData>
			{
				public static readonly PropertyInfo<string> ChildContentsProperty =
					RegisterProperty<string>(_ => _.ChildContents);
				public string ChildContents
				{
					get => this.GetProperty(ChildData.ChildContentsProperty)!;
					set => this.SetProperty(ChildData.ChildContentsProperty, value);
				}
			}			
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class Data
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Data.ContentsProperty
					context.WriteMobileObject(this.ReadProperty<global::Domains.ChildData>(global::Domains.Data.ContentsProperty));
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Data.ContentsProperty
					this.LoadProperty(global::Domains.Data.ContentsProperty, context.ReadMobileObject<global::Domains.ChildData>()!);
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[("Domains.Data_GeneratorSerialization.g.cs", generatedCode)],
			[]);
	}
}