namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs;

public sealed class DuplicateTests
{
	[Test]
	public async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable
			
			namespace Domains;

			[GeneratorSerializable]
			public sealed partial class Node
				: BusinessBase<Node>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<Node?> LeftProperty =
					RegisterProperty<Node?>(_ => _.Left!);
				public Node? Left
				{
					get => this.GetProperty(Node.LeftProperty);
					set => this.SetProperty(Node.LeftProperty, value);
				}

				public static readonly PropertyInfo<Node?> RightProperty =
					RegisterProperty<Node?>(_ => _.Right!);
				public Node? Right
				{
					get => this.GetProperty(Node.RightProperty);
					set => this.SetProperty(Node.RightProperty, value);
				}

				public static readonly PropertyInfo<string> NameProperty =
					RegisterProperty<string>(_ => _.Name);
				public string Name
				{
					get => this.GetProperty(Node.NameProperty)!;
					set => this.SetProperty(Node.NameProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class Node
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Node.NameProperty
					var value0 = this.ReadProperty<string>(global::Domains.Node.NameProperty)!;
					
					if (value0 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value0);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					// global::Domains.Node.LeftProperty
					context.Write(this.ReadProperty<global::Domains.Node?>(global::Domains.Node.LeftProperty), true);
					
					// global::Domains.Node.RightProperty
					context.Write(this.ReadProperty<global::Domains.Node?>(global::Domains.Node.RightProperty), true);
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Node.NameProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.Node.NameProperty, context.Reader.ReadString());
					}
					
					// global::Domains.Node.LeftProperty
					this.LoadProperty(global::Domains.Node.LeftProperty, context.Read<global::Domains.Node>(true)!);
					
					// global::Domains.Node.RightProperty
					this.LoadProperty(global::Domains.Node.RightProperty, context.Read<global::Domains.Node>(true)!);
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[("Domains.Node_GeneratorSerialization.g.cs", generatedCode)],
			[]);
	}
}