using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs;

internal static class ReadOnlyTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable

			namespace Domains;

			[GeneratorSerializable]
			public sealed partial class Data
				: ReadOnlyBase<Data>
			{
				public static readonly PropertyInfo<string> StringContentsProperty =
					RegisterProperty<string>(_ => _.StringContents);
			   public string StringContents => this.GetProperty(Data.StringContentsProperty)!;

			   public static readonly PropertyInfo<ChildData> ChildContentsProperty =
					RegisterProperty<ChildData>(_ => _.ChildContents);
			   public ChildData ChildContents => this.GetProperty(Data.ChildContentsProperty)!;

			   public static readonly PropertyInfo<int> Int32ContentsProperty =
					RegisterProperty<int>(_ => _.Int32Contents);
			   public int Int32Contents => this.GetProperty(Data.Int32ContentsProperty);
			}

			[GeneratorSerializable]
			public sealed partial class ChildData
				: ReadOnlyBase<ChildData>
			{
				public static readonly PropertyInfo<string> ValueProperty =
					RegisterProperty<string>(_ => _.Value);
				public string Value => this.GetProperty(ChildData.ValueProperty)!;
			}
			""";

		var dataGeneratedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class Data
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Data.Int32ContentsProperty
					context.Writer.Write(this.ReadProperty<int>(global::Domains.Data.Int32ContentsProperty));
					
					// global::Domains.Data.StringContentsProperty
					var value1 = this.ReadProperty<string>(global::Domains.Data.StringContentsProperty)!;
					
					if (value1 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value1);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					// global::Domains.Data.ChildContentsProperty
					context.Write(this.ReadProperty<global::Domains.ChildData>(global::Domains.Data.ChildContentsProperty), true);
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Data.Int32ContentsProperty
					this.LoadProperty(global::Domains.Data.Int32ContentsProperty, context.Reader.ReadInt32());
					
					// global::Domains.Data.StringContentsProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.Data.StringContentsProperty, context.Reader.ReadString());
					}
					
					// global::Domains.Data.ChildContentsProperty
					this.LoadProperty(global::Domains.Data.ChildContentsProperty, context.Read<global::Domains.ChildData>(true)!);
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		var childGeneratedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class ChildData
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.ChildData.ValueProperty
					var value0 = this.ReadProperty<string>(global::Domains.ChildData.ValueProperty)!;
					
					if (value0 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value0);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.ChildData.ValueProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.ChildData.ValueProperty, context.Reader.ReadString());
					}
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[
				("Domains.Data_GeneratorSerialization.g.cs", dataGeneratedCode),
				("Domains.ChildData_GeneratorSerialization.g.cs", childGeneratedCode)],
			[]);
	}
}