namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs;

public sealed class SealedTests
{
	[Test]
	public async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			namespace Domains;

			[GeneratorSerializable]
			public partial class BaseData
				: BusinessBase<BaseData>
			{
				public static readonly PropertyInfo<string> CoreProperty =
					BaseData.RegisterProperty<string>(_ => _.Core);
				public string Core
				{
					get => this.GetProperty(BaseData.CoreProperty);
					set => this.SetProperty(BaseData.CoreProperty, value);
				}
			}

			[GeneratorSerializable]
			public sealed partial class DerivedData
				: BaseData
			{
				public static readonly PropertyInfo<int> CustomProperty =
					DerivedData.RegisterProperty<int>(typeof(DerivedData), new PropertyInfo<int>(nameof(DerivedData.Custom)));
				public int Custom
				{
					get => this.GetProperty(DerivedData.CustomProperty);
					set => this.SetProperty(DerivedData.CustomProperty, value);
				}
			}

			[GeneratorSerializable]
			public sealed partial class ConsumingData
				: BusinessBase<ConsumingData>
			{
				public static readonly PropertyInfo<BaseData> ContentsProperty =
					RegisterProperty<BaseData>(_ => _.Contents);
				public BaseData Contents
				{
					get => this.GetProperty(ConsumingData.ContentsProperty);
					set => this.SetProperty(ConsumingData.ContentsProperty, value);
				}
			}
			""";

		var baseDataGeneratedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public partial class BaseData
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.BaseData.CoreProperty
					var value0 = this.ReadProperty<string>(global::Domains.BaseData.CoreProperty)!;
					
					if (value0 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value0);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.BaseData.CoreProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.BaseData.CoreProperty, context.Reader.ReadString());
					}
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		var derivedDataGeneratedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class DerivedData
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.BaseData.CoreProperty
					var value0 = this.ReadProperty<string>(global::Domains.BaseData.CoreProperty)!;
					
					if (value0 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value0);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					// global::Domains.DerivedData.CustomProperty
					context.Writer.Write(this.ReadProperty<int>(global::Domains.DerivedData.CustomProperty));
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.BaseData.CoreProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.BaseData.CoreProperty, context.Reader.ReadString());
					}
					
					// global::Domains.DerivedData.CustomProperty
					this.LoadProperty(global::Domains.DerivedData.CustomProperty, context.Reader.ReadInt32());
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		var consumingDataGeneratedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class ConsumingData
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.ConsumingData.ContentsProperty
					context.Write(this.ReadProperty<global::Domains.BaseData>(global::Domains.ConsumingData.ContentsProperty), false);
					
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.ConsumingData.ContentsProperty
					this.LoadProperty(global::Domains.ConsumingData.ContentsProperty, context.Read<global::Domains.BaseData>(false)!);
					
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[
				("Domains.BaseData_GeneratorSerialization.g.cs", baseDataGeneratedCode),
				("Domains.DerivedData_GeneratorSerialization.g.cs", derivedDataGeneratedCode),
				("Domains.ConsumingData_GeneratorSerialization.g.cs", consumingDataGeneratedCode)
			],
			[]);
	}
}