using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs;

internal static class UnionTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable
			
			namespace Domains;

			public union Identifier(string, int, Guid);

			[GeneratorSerializable]
			public partial class Customer
				: BusinessBase<Customer>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<Identifier> IdentifierProperty =
					Customer.RegisterProperty<Identifier>(_ => _.Identifier);
				public Identifier Identifier
				{
					get => this.GetProperty(Customer.IdentifierProperty);
					set => this.SetProperty(Customer.IdentifierProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			using CslaGeneratorSerialization.Analysis.Extensions;

			#nullable enable
			
			namespace Domains;
			
			public partial class Customer
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Customer.IdentifierProperty
					var value0 = this.ReadProperty<global::Domains.Identifier>(global::Domains.Customer.IdentifierProperty)!;
					context.WriteUnion(value0, new global::System.Collections.Generic.List<byte>());
					
					// General Serialization
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Customer.IdentifierProperty
					{
						var typeIdentifiers = context.Reader.ReadByteArray();
						var typeIdentifiersIndex = 0;
						this.LoadProperty(global::Domains.Customer.IdentifierProperty, (global::Domains.Identifier)context.ReadUnion<global::Domains.Identifier>(typeIdentifiers, typeIdentifiersIndex));
					}
					
					// General Deserialization
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
					((global::Csla.Serialization.Mobile.ISerializationNotification)this).Deserialized();
				}
			}
			
			""";

		var readerExtensionsCode =
			"""
			// <auto-generated/>
			
			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			internal static class GeneratorFormatterReaderContextExtensions
			{
				extension(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					public object ReadUnion<T>(byte[] typeIdentifiers, int typeIdentifierIndex)
					{
						return new object();
					}
				}
			}
			
			""";

		var writerExtensionsCode =
			"""
			// <auto-generated/>
			
			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			internal static class GeneratorFormatterWriterContextExtensions
			{
			    extension(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
			    {
					public void WriteUnion(global::Domains.Identifier value, global::System.Collections.Generic.List<byte> typeIdentifiers)
					{
						switch(value)
						{
							case string u0:
								typeIdentifiers.Add(0);
								break;
							case int u1:
								typeIdentifiers.Add(1);
								break;
							case global::System.Guid u2:
								typeIdentifiers.Add(2);
								break;
						}
					}
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[
				("Domains.Customer_GeneratorSerialization.g.cs", generatedCode),
				("GeneratorFormatterReaderContextExtensions.g.cs", readerExtensionsCode),
				("GeneratorFormatterWriterContextExtensions.g.cs", writerExtensionsCode)
			],
			[]);
	}

	// TODO:
	// Unions with unions
	// Recursive unions (though this can't be done until TypeReferenceModel is fixed)
}