using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs;

internal static class UnionTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable
			
			namespace Domains;

			public sealed record Cat(string Description);
			public sealed record Dog(string Name);

			public union Pet(Cat, Dog);

			[GeneratorSerializable]
			public partial class Owner
				: BusinessBase<Owner>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<Pet> PetProperty =
					Customer.RegisterProperty<Pet>(_ => _.Pet);
				public Pet Pet
				{
					get => this.GetProperty(Owner.PetProperty);
					set => this.SetProperty(Owner.PetProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public partial class Owner
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Owner.PetProperty
					var value0 = this.ReadProperty<global::Domains.Pet>(global::Domains.Owner.PetProperty)!;
					context.WriteUnion(value0);
					
					// General Serialization
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Owner.PetProperty
					this.LoadProperty(global::Domains.Owner.PetProperty, context.ReadUnion<global::Domains.Pet>());
					
					// General Deserialization
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
					((global::Csla.Serialization.Mobile.ISerializationNotification)this).Deserialized();
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[("Domains.Owner_GeneratorSerialization.g.cs", generatedCode)],
			[]);
	}

	// TODO:
	// Unions with unions
	// Recursive unions (though this can't be done until TypeReferenceModel is fixed)
}