using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests.Generators.Graphs;

internal static class UnionTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable
			
			namespace Domains;

			public union Identifier(string, int, Guid);

			[GeneratorSerializable]
			public partial class Customer
				: BusinessBase<Customer>
			{
				[Create]
				private void Create() { }

				public static readonly PropertyInfo<Identifier> IdentifierProperty =
					Customer.RegisterProperty<Identifier>(_ => _.Identifier);
				public Identifier Identifier
				{
					get => this.GetProperty(Customer.IdentifierProperty);
					set => this.SetProperty(Customer.IdentifierProperty, value);
				}
			}
			""";

		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public partial class Customer
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.Customer.IdentifierProperty
					var value0 = this.ReadProperty<global::Domains.Identifier>(global::Domains.Customer.IdentifierProperty)!;
					context.WriteUnion(value0);
					
					// General Serialization
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.Customer.IdentifierProperty
					this.LoadProperty(global::Domains.Customer.IdentifierProperty, context.ReadUnion<global::Domains.Identifier>());
					
					// General Deserialization
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
					((global::Csla.Serialization.Mobile.ISerializationNotification)this).Deserialized();
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[("Domains.Customer_GeneratorSerialization.g.cs", generatedCode)],
			[]);
	}

	// TODO:
	// Unions with unions
	// Recursive unions (though this can't be done until TypeReferenceModel is fixed)
}