using CslaGeneratorSerialization.Analysis.Extensions;
using CslaGeneratorSerialization.Analysis.Models;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;

namespace CslaGeneratorSerialization.Analysis.Builders;

internal sealed class GeneratorFormatterReaderContextExtensionsBuilder
{
	internal GeneratorFormatterReaderContextExtensionsBuilder(List<TypeReferenceModel> unionTypes)
	{
		using var writer = new StringWriter();
		using var indentWriter = new IndentedTextWriter(writer, "\t");

		indentWriter.WriteLines(
			"""
			// <auto-generated/>
			using CslaGeneratorSerialization.Extensions;

			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable

			internal static class GeneratorFormatterReaderContextExtensions
			{
				extension(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
			""");

		indentWriter.Indent += 2;

		GeneratorFormatterReaderContextExtensionsBuilder.BuildReadUnion(
			indentWriter, unionTypes);

		indentWriter.Indent -= 2;

		indentWriter.WriteLines(
			"""
				}
			}
			"""); 
			this.Text = SourceText.From(writer.ToString(), Encoding.UTF8);
		this.FileName = "GeneratorFormatterReaderContextExtensions.g.cs";
	}

	private static void BuildReadUnion(IndentedTextWriter indentWriter, List<TypeReferenceModel> unionTypes)
	{
		indentWriter.WriteLines(
			$$"""
			public object ReadUnion<T>(byte[] typeIdentifiers, int typeIdentifierIndex)
			{
			""");

		indentWriter.Indent++;
		// TODO: lots of code
		indentWriter.WriteLine("return new object();");

		indentWriter.Indent--;

		indentWriter.WriteLines(
			"""
			}
			""");
	}

	internal string FileName { get; }
	internal SourceText Text { get; private set; }
}