using CslaGeneratorSerialization.Analysis.Extensions;
using CslaGeneratorSerialization.Analysis.Models;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;

namespace CslaGeneratorSerialization.Analysis.Builders;

internal sealed class GeneratorFormatterWriterContextExtensionsBuilder
{
	internal GeneratorFormatterWriterContextExtensionsBuilder(List<TypeReferenceModel> unionTypes)
	{
		using var writer = new StringWriter();
		using var indentWriter = new IndentedTextWriter(writer, "\t");

		indentWriter.WriteLines(
			"""
			// <auto-generated/>
			
			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable

			internal static class GeneratorFormatterWriterContextExtensions
			{
				extension(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
			""");

		indentWriter.Indent += 2;

		foreach (var unionType in unionTypes)
		{
			GeneratorFormatterWriterContextExtensionsBuilder.BuildWriteUnion(
				indentWriter, unionType);
		}

		indentWriter.Indent -= 2;

		indentWriter.WriteLines(
			"""
				}
			}
			""");

		this.Text = SourceText.From(writer.ToString(), Encoding.UTF8);
		this.FileName = "GeneratorFormatterWriterContextExtensions.g.cs";
	}

	private static void BuildWriteUnion(IndentedTextWriter indentWriter, TypeReferenceModel unionType)
	{
		indentWriter.WriteLines(
			$$"""
			public void WriteUnion({{unionType.FullyQualifiedName}} value, global::System.Collections.Generic.List<byte> typeIdentifiers)
			{
				switch(value)
				{
			""");
		indentWriter.Indent += 2;

		for (var i = 0; i < unionType.UnionCaseTypes.Length; i++)
		{
			var unionCaseType = unionType.UnionCaseTypes[i];

			indentWriter.WriteLines(
				$$"""
				case {{unionCaseType.FullyQualifiedName}} u{{i}}:
					typeIdentifiers.Add({{i}});
				""");

			indentWriter.Indent++;

			// TODO: handle if union or non-union

			indentWriter.WriteLine("break;");
			indentWriter.Indent--;
		}

		indentWriter.Indent -= 2;

		indentWriter.WriteLines(
			"""
				}
			}
			""");
	}

	internal string FileName { get; }
	internal SourceText Text { get; private set; }
}