using CslaGeneratorSerialization.Analysis.Extensions;
using CslaGeneratorSerialization.Analysis.Models;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;

namespace CslaGeneratorSerialization.Analysis.Builders;

internal sealed class GeneratorFormatterWriterContextExtensionsBuilder
{
	internal GeneratorFormatterWriterContextExtensionsBuilder(List<TypeReferenceModel> unionTypes)
	{
		using var writer = new StringWriter();
		using var indentWriter = new IndentedTextWriter(writer, "\t");

		indentWriter.WriteLines(
			"""
			// <auto-generated/>
			using CslaGeneratorSerialization.Extensions;

			namespace CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable

			internal static class GeneratorFormatterWriterContextExtensions
			{
				extension(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
			""");

		indentWriter.Indent += 2;

		foreach (var unionType in unionTypes)
		{
			GeneratorFormatterWriterContextExtensionsBuilder.BuildWriteUnion(
				indentWriter, unionType);
		}

		indentWriter.Indent -= 2;

		indentWriter.WriteLines(
			"""
				}
			}
			""");

		this.Text = SourceText.From(writer.ToString(), Encoding.UTF8);
		this.FileName = "GeneratorFormatterWriterContextExtensions.g.cs";
	}

	private static void BuildWriteUnion(IndentedTextWriter indentWriter, TypeReferenceModel unionType)
	{
		indentWriter.WriteLines(
			$$"""
			public void WriteUnion({{unionType.FullyQualifiedName}} value, global::System.Collections.Generic.List<byte> typeIdentifiers)
			{
				switch(value)
				{
			""");
		indentWriter.Indent += 2;

		if (unionType.UnionCaseTypes.Any(unionType => unionType.IsNullable || !unionType.IsValueType))
		{
			// We have a null check first, as the union's Value property
			// will just be assigned to null in that case. We don't
			// care what case type was null.
			indentWriter.WriteLines(
				$$"""
				case null:
					typeIdentifiers.Add({{unionType.UnionCaseTypes.Length}});
					context.Writer.Write((typeIdentifiers.Count, typeIdentifiers.ToArray()));
					break;
				""");
		}

		for (var i = 0; i < unionType.UnionCaseTypes.Length; i++)
		{
			var unionCaseType = unionType.UnionCaseTypes[i];
			var valueVariable = $"u{i}";
			var switchCaseType = unionCaseType.IsNullable && unionCaseType.IsValueType ?
				unionCaseType.FullyQualifiedNameNoNullableAnnotation :
				unionCaseType.FullyQualifiedName;
			indentWriter.WriteLines(
				$$"""
				case {{switchCaseType}} {{valueVariable}}:
					typeIdentifiers.Add({{i}});
				""");

			indentWriter.Indent++;

			if (unionCaseType.UnionCaseTypes.Length == 0)
			{
				indentWriter.WriteLine("context.Writer.Write((typeIdentifiers.Count, typeIdentifiers.ToArray()));");
			}

			OperationBuilder.BuildUnionWriteOperation(indentWriter, unionCaseType, valueVariable, true);

			indentWriter.WriteLine("break;");
			indentWriter.Indent--;
		}

		indentWriter.Indent -= 2;

		indentWriter.WriteLines(
			"""
				}
			}
			""");
	}

	internal string FileName { get; }
	internal SourceText Text { get; private set; }
}