using NUnit.Framework;

namespace CslaGeneratorSerialization.Analysis.Tests;

internal static class ImplementPropertiesTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Csla;
			using CslaGeneratorSerialization;
			using System;

			#nullable enable
			
			namespace Csla
			{
				[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false)]
				public class CslaImplementPropertiesAttribute : Attribute;

				[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
				public class CslaIgnorePropertyAttribute : Attribute;
			}

			namespace Domains
			{
				[GeneratorSerializable]
				[CslaImplementProperties]
				public sealed partial class StateData
					: BusinessBase<StateData>
				{
					[Create]
					private void Create() { }

					public static readonly PropertyInfo<string> ContentsProperty =
						RegisterProperty<string>(nameof(StateData.Contents));
					public string Contents
					{
						get => this.GetProperty(StateData.ContentsProperty)!;
						set => this.SetProperty(StateData.ContentsProperty, value);
					}

					public partial Guid Id { get; set; }

					[CslaIgnoreProperty]
					public partial uint Value { get; set; }
				}

				public sealed partial class StateData
					: BusinessBase<StateData>
				{
					private uint value;
					private Guid id;
	
					public static readonly PropertyInfo<Guid> IdProperty =
						RegisterProperty<Guid>(nameof(StateData.Id));
					public partial Guid Id { get => this.id; set => this.id = value; }
					
					public partial uint Value { get => this.value; set => this.value = value; }
				}
			}
			""";

		// It may look weird, but there's a reason IdProperty ends up being serialized twice.
		// Our SG is looking for properties that [CslaImplementProperties] will generate
		// managed backing fields for.
		// We have to "fake" what this generator does, so we create a partial class
		// in the code that has a managed backing field for the Id property 
		// (otherwise, we'd get a compilation error in this test).
		// But by doing that, our SG is going to pick that up, and it
		// ends up handling Id twice. This won't happen in "real" code;
		// it's just a bit of an anomaly in this test case.
		var generatedCode =
			"""
			// <auto-generated/>
			
			using CslaGeneratorSerialization.Extensions;
			using CslaGeneratorSerialization.Analysis.Extensions;
			
			#nullable enable
			
			namespace Domains;
			
			public sealed partial class StateData
				: global::CslaGeneratorSerialization.IGeneratorSerializable
			{
				void global::CslaGeneratorSerialization.IGeneratorSerializable.SetState(global::CslaGeneratorSerialization.GeneratorFormatterWriterContext context)
				{
					// global::Domains.StateData.ContentsProperty
					var value0 = this.ReadProperty<string>(global::Domains.StateData.ContentsProperty)!;
					if (value0 is not null)
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Value);
						context.Writer.Write(value0);
					}
					else
					{
						context.Writer.Write((byte)global::CslaGeneratorSerialization.SerializationState.Null);
					}
					
					// global::Domains.StateData.IdProperty
					var value1 = this.ReadProperty<global::System.Guid>(global::Domains.StateData.IdProperty)!;
					context.Writer.Write(value1);
					
					// global::Domains.StateData.IdProperty
					var value2 = this.ReadProperty<global::System.Guid>(global::Domains.StateData.IdProperty)!;
					context.Writer.Write(value2);
					
					// General Serialization
					var metastate = ((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).GetMetastate();
					context.Writer.Write((metastate.Length, metastate));
				}
				
				void global::CslaGeneratorSerialization.IGeneratorSerializable.GetState(global::CslaGeneratorSerialization.GeneratorFormatterReaderContext context)
				{
					// global::Domains.StateData.ContentsProperty
					if (context.Reader.ReadStateValue() == global::CslaGeneratorSerialization.SerializationState.Value)
					{
						this.LoadProperty(global::Domains.StateData.ContentsProperty, context.Reader.ReadString());
					}
					
					// global::Domains.StateData.IdProperty
					this.LoadProperty(global::Domains.StateData.IdProperty, new global::System.Guid(context.Reader.ReadBytes(16)));
					
					// global::Domains.StateData.IdProperty
					this.LoadProperty(global::Domains.StateData.IdProperty, new global::System.Guid(context.Reader.ReadBytes(16)));
					
					// General Deserialization
					((global::Csla.Serialization.Mobile.IMobileObjectMetastate)this).SetMetastate(context.Reader.ReadByteArray());
					((global::Csla.Serialization.Mobile.ISerializationNotification)this).Deserialized();
				}
			}
			
			""";

		await TestAssistants.RunGeneratorAsync<GeneratorSerializationGenerator>(code,
			[("Domains.StateData_GeneratorSerialization.g.cs", generatedCode)],
			[]);
	}
}
